feature/metas
udistrital/necesidades_cliente pull request #255
Opened 2021-08-27 17:34 UTC by brayanpasa99

…alor a la fuente de financiamiento

Pull Request con relación a los issue #250, #251 y el pull request generado por @DanKazuky (#254)

Se integra la selección de los planes de adquisición para poder obtener la vigencia y traer diferentes rubros del árbol de rubros. Se hacen cambios en la obtención de metas y actividades apuntando al API de Plan de Adquisiciones en vez de a bodeha jbpm.

Falta considerar:

* [ ] Eliminación de código redundante y/o innecesario.
* [ ] Ajuste de los datos y verificación de la obtención de los mismos de la base de datos.

2021-08-27 22:16 UTC, AlexFBP requested changes
En general / para la próxima, evitar ajustar la indentación: mantener los mismos espacios al comienzo de la línea, sobretodo cuando más de una persona está trabajando sobre un mismo archivo...

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/controllers/necesidad/solicitud_necesidad.js
> +        self.planes_anuales = [{}];
- `[{}]`: Un arreglo de longitud 1, cuyo único elemento es un objeto vacío
- `[]`: Un arreglo vacío

```suggestion
        self.planes_anuales = [];
```

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/controllers/necesidad/solicitud_necesidad.js
> +                    if(response.data.Data[0]!== undefined){
```suggestion
                    if(response.data.Data[0] !== undefined){
```

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/services/metas_service.js
>                      return $http.get(path + tabla, [{ timeout: cancelSearch.promise }, token_service.setting_bearer.headers]);
Eliminar el código viejo, de todas maneras ya está en Git...
(eliminar el bloque comentado)

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/services/plan_adquisiciones_service.js
> +  });
**GENERAL:** (Donde haga falta) Dejar una línea vacía al final del archivo

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/apropiaciones/lista_apropiaciones.js
> +              $scope.tipofinanciacion != undefined
Dejar como estaba antes:
```suggestion
              $scope.unidadejecutora !== undefined &&
              $scope.tipofinanciacion !== undefined
```
... o por qué se cambió?

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +              )
- Por legibilidad, dejar la consulta en una variable externa:
  ```javascript
  const QUERY = "..."
  metasRequest.get(QUERY). ...
  ```
- (Considerar) eliminar el bloque de código comentado (o indicar en un comentario adicional -en código- el propósito)

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +                      if (uniqueMeta.Id != metaSchema.Id) {
```suggestion
                      if (uniqueMeta.Id !== metaSchema.Id) {
```

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +                          console.log("F", f);
**GENERAL**: comentar o eliminar llamadas a consola

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +            console.log("SELF ACTIVIDADES", self.actividades);
comentar o eliminar...

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +                  console.log("FUENTESACT", fuentesact);
...

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +                  console.log(res);
...

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +              "1"*/
- Eliminar código viejo comentado
- Usar una `const` para el query, por legibilidad (sobra decir que antes del `return`)

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +                $scope.apropiacion.Apropiacion.Vigencia*/
Eliminar o agregar un comentario que explique este bloque...

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +            //que están en la tabla ya tengan ese filtro $scope.dependenciasolicitante.toString()
```suggestion
            // el número de dependencia solicitante se espera que los rubros
            // que están en la tabla ya tengan ese filtro $scope.dependenciasolicitante.toString()
```

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +                      uniqueActividad.actividad_id !=
```suggestion
                      uniqueActividad.actividad_id !==
```

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +            });*/
Si este código ya no se va a usar, se reemplazó, mejor eliminarlo

2021-08-27 22:16 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +              if (self.gridOptions.data.length <= 5) {
```suggestion
              if (self.gridOptions.data.length <== 5) {
```

2021-08-28 02:02 UTC, brayanpasa99 commented on app/scripts/controllers/necesidad/solicitud_necesidad.js
> +        self.planes_anuales = [{}];
Se modifica para dejarlo como un arreglo vacío

2021-08-28 02:02 UTC, brayanpasa99 commented on app/scripts/controllers/necesidad/solicitud_necesidad.js
> +        self.planes_anuales = [{}];
Se modifica para dejarlo como un arreglo vacío

2021-08-28 02:02 UTC, brayanpasa99 commented on app/scripts/controllers/necesidad/solicitud_necesidad.js
> +                    if(response.data.Data[0]!== undefined){
Se realizan los cambios sugeridos

2021-08-28 02:03 UTC, brayanpasa99 commented on app/scripts/services/metas_service.js
>                      return $http.get(path + tabla, [{ timeout: cancelSearch.promise }, token_service.setting_bearer.headers]);
Se deja solo la petición get usada

2021-08-28 02:03 UTC, brayanpasa99 commented on app/scripts/services/plan_adquisiciones_service.js
> +  });
Se aplica el formato de VS y se deja una línea vacía al final del archivo

2021-08-28 02:04 UTC, brayanpasa99 commented on app/scripts/directives/apropiaciones/lista_apropiaciones.js
> +              $scope.tipofinanciacion != undefined
Se cambió para hacer pruebas sobre la validación del árbol con el año 2021, sin embargo, se deja el modo estricto de comparación

2021-08-28 02:07 UTC, brayanpasa99 commented on app/scripts/directives/metas/metas-actividades.js
> +              )
Se elimina la consulta adicional y se separa el query en una variable externa.

2021-08-28 02:07 UTC, brayanpasa99 commented on app/scripts/directives/metas/metas-actividades.js
> +                      if (uniqueMeta.Id != metaSchema.Id) {
Se cambia a modo estricto

2021-08-28 02:08 UTC, brayanpasa99 commented on app/scripts/directives/metas/metas-actividades.js
> +                          console.log("F", f);
Se elimina la llamada en consola.

2021-08-28 02:09 UTC, brayanpasa99 commented on app/scripts/directives/metas/metas-actividades.js
> +            console.log("SELF ACTIVIDADES", self.actividades);
Se elimina la llamada a consola

2021-08-28 02:09 UTC, brayanpasa99 commented on app/scripts/directives/metas/metas-actividades.js
> +                  console.log("FUENTESACT", fuentesact);
Se elimina llamada a consola

2021-08-28 02:10 UTC, brayanpasa99 commented on app/scripts/directives/metas/metas-actividades.js
> +                  console.log(res);
Se elimina llamada a consola.

2021-08-28 02:11 UTC, brayanpasa99 commented on app/scripts/directives/metas/metas-actividades.js
> +              "1"*/
Se realizan las correcciones pertinentes

2021-08-28 02:13 UTC, brayanpasa99 commented on app/scripts/directives/metas/metas-actividades.js
> +            //que están en la tabla ya tengan ese filtro $scope.dependenciasolicitante.toString()
Solucionado

2021-08-28 02:13 UTC, brayanpasa99 commented on app/scripts/directives/metas/metas-actividades.js
> +                      uniqueActividad.actividad_id !=
Solucionado

2021-08-28 02:15 UTC, brayanpasa99 commented on app/scripts/directives/metas/metas-actividades.js
> +            });*/
Se espera realizar una inspección profunda del código comentado antes de eliminarlo, por lo tanto se deja el código por el momento

2021-08-28 02:17 UTC, brayanpasa99 commented on app/scripts/directives/metas/metas-actividades.js
> +              if (self.gridOptions.data.length <= 5) {
No se realiza el cambio sugerido porque el programa lanza error, el menor que o igual aparentemente no tiene modo de comparación estricta

2021-08-29 23:34 UTC, AlexFBP reviewed
(ver comentarios)

2021-08-29 23:34 UTC, AlexFBP commented on app/scripts/environment/environment.js
> +            PLAN_ADQUISISIONES_MID_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/plan_adquisiciones_mid/v1/',
Falta pasar esta variable a environment_test y environment_prod
(o eliminarla acá)

2021-08-29 23:34 UTC, AlexFBP commented on app/scripts/controllers/necesidad/solicitud_necesidad.js
> +            }
Hay la posibilidad de que `res.data.Body === null`?
Es decir, que sea nulo y aún así sea válido?
Digamos, cuando el plan de adquisiciones esté vacío...

2021-08-29 23:34 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +                  }
Aprovechando las funciones de [Array](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Array), esto se puede reescribir un poco para separar las responsabilidades y desacoplar un poco el código:

```suggestion
                self.metas = res.data.filter((meta) => {
                  // (reescribir) la condición evaluada en las lineas 96-104
                }).map( meta => {
                  // La transformación realizada en las lineas 88-94
```
(Nota: cambio sugerido, no es necesario aplicarlo)
(inclusive, el `.filter()` podría hacerse desde el query?)

2021-08-29 23:34 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +                  self.gridOptions.data.push(actividadSchema);
De manera similar, podría ser posible replantear este bloque como...:
```javascript
self.gridOptions.data = res.data.filter(...).map(...);
```

2021-08-29 23:34 UTC, AlexFBP commented on app/scripts/directives/metas/metas-actividades.js
> +                self.gridOptions.paginationPageSize ||
Puede que hagan falta los siguientes `()` para desambiguar?

```suggestion
              ( (self.gridOptions.data.length <=
                self.gridOptions.paginationPageSize) ||
```

(En cualquier caso, es posible que hagan falta un par de `()`, con el mero objetivo de clarificar)

2021-08-30 15:32 UTC, brayanpasa99 commented on app/scripts/controllers/necesidad/solicitud_necesidad.js
> +            }
Si no me equivoco el Body entraría en ese caso como [] y no como null, confirmar por favor @DanKazuky

2021-08-30 15:58 UTC, brayanpasa99 commented on app/scripts/directives/metas/metas-actividades.js
> +                  }
No se realiza porque tengo una confusión de cómo podría aplicar el filter en este caso, lo que se busca es que no se imprima más de una meta con el mismo id, se plantea discusión para daily

2021-08-30 18:05 UTC, AlexFBP approved these changes

2021-08-30 18:10 UTC, merged