feat: Ajuste Editar necesidad
udistrital/necesidades_cliente pull request #293
Opened 2021-11-24 14:43 UTC by DanKazuky

Se cambio que al recibir la necesidad consultada los datos de los rubros no se guarden directamente en la estructura de la necesidad, se guardan en una variable aparte para que cuando se realice la seccion de la financiacion, se puedan colocar los cambios deseados sin restricciones (Que en la vista se carguen las tablas y los datos para cambiar), se cambia el orden de vista los campos unidad ejecutora con el tipo de financiacion segun peticion del product owner y se limita el flujo para desplegar financiacion.

2021-11-25 01:27 UTC, AlexFBP requested changes

2021-11-25 01:27 UTC, AlexFBP commented on app/scripts/controllers/necesidad/solicitud_necesidad.js
> +          }): _;
(En general y/o donde aplique) Uso innecesario de ternas, si no se necesita el valor retornado por una terna usar un if-else común...
```suggestion
          if (self.Necesidad.DependenciaNecesidadId.OrdenadorGastoId) {
            necesidadService
            .get_info_dependencia(self.Necesidad.DependenciaNecesidadId.OrdenadorGastoId)
            .then(function (response) {
                self.rol_ordenador_gasto = response.dependencia.Id;
            });
          }
```

2021-11-25 01:27 UTC, AlexFBP commented on app/scripts/controllers/necesidad/solicitud_necesidad.js
> +            )): _;
```suggestion
            if (self.Necesidad.DependenciaNecesidadId.InterventorId) {
              self.dependencia_supervisor = necesidadService
                .getInfoPersonaNatural( self.Necesidad.DependenciaNecesidadId.InterventorId );
            }
```

2021-11-25 01:27 UTC, AlexFBP commented on app/scripts/controllers/necesidad/solicitud_necesidad.js
> +          }): _;
```suggestion
          if (r.Productos) {
            r.Productos.forEach( function (p) {
              if (p.InfoProducto) {
                p = _.merge(p, p.InfoProducto)); // mezclar la info de productos de plan cuentas con la de necesidades
              }
            });
          }
```

2021-11-25 01:27 UTC, AlexFBP commented on app/scripts/directives/necesidad/visualizar_necesidad.js
> +                                        "%2CRegistroPlanAdquisicionesId__ResponsableId%3A" + response_dependencia.data[0].Id + "&limit=-1").then(function (response) {
Mucha responsabilidad en una misma línea...
```suggestion
                                    const queryMetas = 'Registro_plan_adquisiciones-Metas_Asociadas?query=RegistroPlanAdquisicionesId__PlanAdquisicionesId__Vigencia%3A' + $scope.necesidad.Necesidad.Vigencia +
                                    "%2CRegistroPlanAdquisicionesId__ResponsableId%3A" + response_dependencia.data[0].Id + "&limit=-1";
                                    metasRequest.get(queryMetas).then(function (response) {
```

2021-11-25 01:27 UTC, AlexFBP commented on app/scripts/directives/necesidad/visualizar_necesidad.js
> +                                return actividad.ActividadId === item.Id;
1. Dado que no se está usando el valor retornado por la terna declarada en la L144, por favor expandir a if/else
2. **Revisar**: Dado que `Array.map()` **no busca sino que transforma**, es altamente posible que...
   - `meta.InfoMeta` termine siendo un arreglo de booleanos
   - `actividad.InfoActividad` termine siendo un arreglo de booleanos
   
   Lo anterior es correcto?

Por si algo revisar:
- [MDN Array.map()](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Array/map)
- [MDN Array.filter()](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)
- [MDN Array.find()](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

2021-12-05 21:28 UTC, DanKazuky commented on app/scripts/directives/necesidad/visualizar_necesidad.js
> +                                return actividad.ActividadId === item.Id;
Efectivamente sucedia lo que dices por lo que se reajusto el codigo para que su funcionalidad fuera la que debe

2021-12-05 21:29 UTC, DanKazuky commented on app/scripts/controllers/necesidad/solicitud_necesidad.js
> +          }): _;
Se ajustaron algunas lineas con respecto a esto pero realmente son tantas que no podría realizar el ajustes de todas en este momento, pero lo tendré en cuenta para cada caso que vea dentro de los desarrollos.

2021-12-05 23:08 UTC, AlexFBP requested changes
En general bien. Se dejaron un par de comentarios, cada uno con un _suggested change_

2021-12-05 23:08 UTC, AlexFBP commented on app/scripts/controllers/necesidad/solicitud_necesidad.js
> +            }): _;
Si no se necesita el valor retornado por una terna, usar un `if`. En general, reducir/evitar el uso de ternas, entre más explícito y legible sea el código, mejor
```suggestion
            if (self.Necesidad.DependenciaNecesidadId.SupervisorId) {
              necesidadService.get_info_dependencia(
                self.Necesidad.DependenciaNecesidadId.SupervisorId
              ).then(function (response) {
                self.dependencia_supervisor = response.dependencia.Id;
              });
            }
```

2021-12-05 23:08 UTC, AlexFBP commented on app/scripts/directives/necesidad/visualizar_necesidad.js
>                                      //TODO: Arreglar llamado a metasRequest
Revisar: Si ya se arregló, quitar esto...
```suggestion
```

2021-12-05 23:39 UTC, DanKazuky commented
https://github.com/udistrital/presupuesto_cliente/issues/468

2021-12-06 03:03 UTC, AlexFBP approved these changes

2021-12-06 03:03 UTC, merged