feat: adicion interceptor en necesidadesCrud
udistrital/necesidades_cliente pull request #294
Opened 2021-11-24 22:54 UTC by DanKazuky

2021-12-01 04:04 UTC, AlexFBP reviewed
De momento, bien. Se responderá, con aprobación si no hay cambios, una vez se quite el estado Draft

2021-12-09 03:06 UTC, AlexFBP requested changes
En general bien
- La mayoría de comentarios que se dejaron fueron _suggested changes_ para agregar espacios  faltantes
- El resto, los "mas relevantes" se dejaron en el archivo `app/scripts/environment/environment.js`

2021-12-09 03:06 UTC, AlexFBP commented on app/scripts/environment/environment.js
> +            //PLAN_CUENTAS_MID_SERVICE: 'http://localhost:8084/v1/',
Eliminar esto
```suggestion
```

2021-12-09 03:06 UTC, AlexFBP commented on app/scripts/environment/environment.js
> +            MOVIMIENTOS_CRUD: "http://localhost:8080/v1/",
- Localhost... Corregir por la URL adecuada del api store de WSO2
- Replicar en los otros environment.js
- Validar que el (token del) cliente de necesidades tenga acceso a este CRUD. En caso que no, solicitar registro en WSO2 a Jhon

2021-12-09 03:06 UTC, AlexFBP commented on app/scripts/directives/apropiaciones/lista_apropiaciones.js
> +                var Movimiento={};
```suggestion
                var Movimiento = {};
```

2021-12-09 03:06 UTC, AlexFBP commented on app/scripts/directives/apropiaciones/lista_apropiaciones.js
> +                var fuenteIdMov= null;
```suggestion
                var rubroMov = null;
                var actividadIdMov = null;
                var fuenteIdMov = null;
```

2021-12-09 03:06 UTC, AlexFBP commented on app/scripts/directives/apropiaciones/lista_apropiaciones.js
> +                        Movimiento.Cuen_Pre =Cuen_Pre;
```suggestion
                        Movimiento.Cuen_Pre = Cuen_Pre;
```

2021-12-09 03:06 UTC, AlexFBP commented on app/scripts/directives/apropiaciones/lista_apropiaciones.js
> +                movimientosCrudRequest.post("movimiento_detalle/postUltimoMovDetalle/",jsonCompleto).then(function(respuestamov){
```suggestion
                movimientosCrudRequest.post("movimiento_detalle/postUltimoMovDetalle/", jsonCompleto).then(function(respuestamov){
```

2021-12-09 03:06 UTC, AlexFBP commented on app/scripts/directives/apropiaciones/lista_apropiaciones.js
> +          $scope.$emit('pasomovimiento',$scope.movimiento);
```suggestion
          $scope.$emit('pasomovimiento', $scope.movimiento);
```

2021-12-09 18:32 UTC, DanKazuky commented on app/scripts/environment/environment.js
> +            MOVIMIENTOS_CRUD: "http://localhost:8080/v1/",
- Corregido el localhost por la URL correcta
- Replicado a los demas enviroment
- Validado (No esta) y solicitado a Jhon, esperando respuesta de parte de Jhon

2021-12-09 18:32 UTC, DanKazuky commented on app/scripts/environment/environment.js
> +            //PLAN_CUENTAS_MID_SERVICE: 'http://localhost:8084/v1/',
Corregido

2021-12-09 18:33 UTC, DanKazuky commented on app/scripts/directives/apropiaciones/lista_apropiaciones.js
> +                var fuenteIdMov= null;
Corregido

2021-12-09 18:34 UTC, DanKazuky commented on app/scripts/directives/apropiaciones/lista_apropiaciones.js
> +                        Movimiento.Cuen_Pre =Cuen_Pre;
Corregido

2021-12-09 18:34 UTC, DanKazuky commented on app/scripts/directives/apropiaciones/lista_apropiaciones.js
> +                var Movimiento={};
Corregido

2021-12-09 18:35 UTC, DanKazuky commented on app/scripts/directives/apropiaciones/lista_apropiaciones.js
> +                movimientosCrudRequest.post("movimiento_detalle/postUltimoMovDetalle/",jsonCompleto).then(function(respuestamov){
Cambiado

2021-12-09 18:41 UTC, AlexFBP approved these changes

2021-12-09 18:41 UTC, merged