Feature/cambio consecutivo
udistrital/necesidades_cliente pull request #325
Opened 2022-02-23 21:36 UTC by DanKazuky

2022-02-24 02:57 UTC, AlexFBP requested changes
Algunos ajustes adicionales y quedaría

2022-02-24 02:57 UTC, AlexFBP commented on package-lock.json
> +{
Eliminar este archivo y asegurarse que esté listado en el .gitignore
(Yarn bloquea sus dependencias con el archivo yarn.lock)
El equivalente de `npm install` es simplemente `yarn`

2022-02-24 02:57 UTC, AlexFBP commented on package.json
> +  "description": "En este repositorio se encuentra el cliente del modulo de resoluciones.",
```suggestion
  "description": "En este repositorio se encuentra el cliente del subsistema de Necesidades",
```

2022-02-24 02:57 UTC, AlexFBP commented on package.json
> +  "version": "1.22.17",
Esta versión de dónde salió, o cómo se generó? De acuerdo al punto en la historia del que surgió esta rama, la última versión publicada al momento en que se creó esta rama es la 0.4.1
![image](https://user-images.githubusercontent.com/6588872/155446500-af9a041b-0341-4474-befe-83ddcd5c2a74.png)
```suggestion
  "version": "0.4.1",
```

2022-02-24 02:57 UTC, AlexFBP commented on package.json
> +  "author": "",
```suggestion
  "author": "OAS Oficina Asesora de Sistemas, UDFJC",
```

2022-02-24 02:57 UTC, AlexFBP commented on app/views/necesidad/solicitud_necesidad.html
> +      <span ng-if="solicitudNecesidad.Necesidad.Consecutivo&&solicitudNecesidad.Necesidad.Consecutivo!=0">
```suggestion
      <span ng-if="solicitudNecesidad.Necesidad.Consecutivo && solicitudNecesidad.Necesidad.Consecutivo != 0">
```

2022-02-24 02:57 UTC, AlexFBP commented on app/views/necesidad/necesidades.html
> +  </style>
```suggestion
#listaNec{
  border: 0;
  width: 100%;
  height: 60vh;
}
</style>
```

De ser posible, mejor mover este estilo a alguno de los archivos en `app/styles`, con el fin de que los HTML por mucho tengan estilos dinámicos, que lo estáticos se traigan de otro lado. Se podría crear un archivo en esa carpeta llamado `necesidades.css`

Adicionalmente, en vez de `id` mejor usar `class` (<-- Esto ultimo no es estrictamente necesario, es una recomendación)

2022-02-24 02:57 UTC, AlexFBP commented on package.json
>      "jslint": "^0.12.1",
Validar si esta dependencia se puede dejar como de desarrollo...
```sh
yarn add jslint@^0.12.1 -D
```

2022-03-01 05:01 UTC, AlexFBP requested changes
Un ajuste menor y quedaría...

2022-03-01 05:01 UTC, AlexFBP commented on app/views/necesidad/necesidades.html
> +#listaNec{
Para que este selector funcione con la L17:
```suggestion
.listaNec{
```

2022-03-04 19:28 UTC, diagutierrezro requested changes

2022-03-04 19:28 UTC, diagutierrezro commented on app/views/necesidad/necesidades.html
> +              <div ui-grid="necesidades.gridOptions" ui-grid-selection ui-grid-pagination class="grid" class="listaNec"></div>
```suggestion
              <div ui-grid="necesidades.gridOptions" ui-grid-selection ui-grid-pagination class="grid listaNec"></div>
```

2022-03-04 19:37 UTC, diagutierrezro approved these changes

2022-03-04 19:38 UTC, AlexFBP approved these changes

2022-03-04 19:39 UTC, merged